# Generated by Django 4.0.6 on 2022-08-16 23:15

import app_data.models
import app_data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=app_data.models.user_directory_path, validators=[app_data.validators.validate_file_extension]),
        ),
    ]
